### PR TITLE
Release

### PR DESCRIPTION
**Pull request by JuiP**

### CODE REVIEW

**Comment by JuiP** [comment]
When I tried running `python setup.py genpot`, this is what I got:
```
po/FlipSticks.pot:9: end-of-line within string
po/FlipSticks.pot:9: keyword "and" unknown
po/FlipSticks.pot:8: missing 'msgstr' section
po/FlipSticks.pot:9:4: syntax error
po/FlipSticks.pot:9: keyword "program" unknown
po/FlipSticks.pot:9: keyword "a" unknown
po/FlipSticks.pot:9: keyword "stick" unknown
po/FlipSticks.pot:9: keyword "figure" unknown
po/FlipSticks.pot:9: keyword "to" unknown
po/FlipSticks.pot:9: keyword "walk" unknown
po/FlipSticks.pot:9: keyword "run" unknown
po/FlipSticks.pot:9: keyword "rotate" unknown
po/FlipSticks.pot:9: keyword "twist" unknown
po/FlipSticks.pot:9: keyword "tumble" unknown
po/FlipSticks.pot:9: keyword "and" unknown
po/FlipSticks.pot:10: keyword "dance" unknown
po/FlipSticks.pot:10: keyword "You" unknown
po/FlipSticks.pot:10: keyword "can" unknown
po/FlipSticks.pot:10: keyword "save" unknown
po/FlipSticks.pot:10: keyword "your" unknown
xgettext: too many errors, aborting
ERROR - xgettext failed with return code 1.
```
This is the first time I encountered something like this, and as a result the modified `.pot` file has just the entries from activity.info. @quozl @chimosky any hints what might be the issue?

**Comment by JuiP** [comment]
@Saumya-Mishra9129 The `right hand` and `left hand` doesnot have a slider that works. I'm not sure if it was intended or a port to Gtk+3 regression. Can you confirm?
I looked at the parts with slider working, seems like left hand and right hand doesnot really have a joint that wasn't considered; I think the two hand option has no meaning than just representing a body part. @quozl @chimosky

**Comment by Saumya-Mishra9129** [comment]
> The `right hand` and `left hand` doesnot have a slider that works. I'm not sure if it was intended or a port to Gtk+3 regression. Can you confirm?

Thanks for noticing. The size slider works , but angle one doesn't work. I think It is intended this way, but I am not sure.

**Comment by JuiP** [comment]
@quozl @chimosky Kindly test, review and merge :)

**Pull request merged**
